### PR TITLE
added  language to html tag

### PR DESCRIPTION
**Pull request by kartikgajjar7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Kartik2220** [comment]
@eddiejaoude plz review this pr :)

**Comment by Kartik2220** [comment]
@naomi-lgbt hey plz review this PR

**Comment by E-fais** [comment]
Can you please explain why you are suggesting this change?

**Review by E-fais — APPROVED** [review]
Since this page contains only English , adding language to HTML will make any difference..?

**Comment by naomi-lgbt** [comment]
According to MDN:

> Note: The default value of lang is unknown, therefore it is recommended to always specify this attribute with the appropriate value.

**Review by naomi-lgbt — APPROVED** [review]
banger pr, thanks for contributing!

**Comment by eddiejaoude** [comment]
Great collaboration everyone 👍

**Pull request merged**
