### PR TITLE
feat: add founder section

### LINKED ISSUE #290: [FEATURE] Founders section?
### Description

Do we need to add the founders section?

Screenshot 2023-11-03 at 17 33 34

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
## Fixes Issue
Closes #290 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

#### Narrow Window
narrow-window
#### Wider Window
wider-window

## Note to reviewers
Hope this works fine. Feel free to give me any feedback. Thanks.

### CODE REVIEW

**Review by xkrishguptaa — CHANGES_REQUESTED** [review]
Hi! Yes, that was the general idea for having that section but we did not want exact duplication as we want to fit it in with the current theme. Please change it to make it fit in the website's colors and theme

**Comment by Satoshi-Sh** [comment]
Just changed the colors to match the website theme.
Screenshot from 2023-12-19 11-55-03

**Review by xkrishguptaa — COMMENTED** [review]
Please also make every thing round edges to match with the rest of the site

**Comment by Satoshi-Sh** [comment]
Thanks for the advice.

I added "round" to the iframes and header section.

**Review by xkrishguptaa — APPROVED** [review]
Thank you for your contribution! We can improve this section more later

**Pull request merged**
