### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by eddiejaoude**
Did we really not deploy this for that long 😱 

Maybe we do not need `develop` anymore and can just use `main`?

### CODE REVIEW

**Comment by eddiejaoude** [comment]
`main` has not been updated since `Sept 2020`, maybe we ditch the current `main` and create a new one from `develop` ?

**Comment by nhcarrigan** [comment]
@eddiejaoude do you have a CD pipeline? Or are deployments done manually?

**Comment by eddiejaoude** [comment]
I have not been doing things manually, but I don't think the automation was running for this branch 🤔 

The GitHub Action for deployment was from `main` and deployed to the wrong branch also 🤦‍♂️ https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/develop/.github/workflows/deploy.yml

I think there must have been some repo changes, and this got missed and we didn't notice.

Screenshot 2021-02-03 at 01 35 23

**Comment by nhcarrigan** [comment]
The benefit of maintaining a `develop` branch, then, would be to allow PRs to merge without requiring a deploy on each PR.

The downside is... this.

**Comment by jai-dewani** [comment]
Oh yeah, I saw that many changes have not been pushed to live but then thought this must a conscious choice.  
We can setup of a cycle period after which the develop branch will be merged into main for deploying to live. Maybe 2 or 3 weeks.

**Comment by eddiejaoude** [comment]
I am thinking lets make it continuous so all little changes go out often and if something is broken, then we keep rolling little changes forwards. Now this is huge and might break but we won't know what broke it

**Pull request closed without merging**
