### PR TITLE
Paraphrasing some lines

### PR DESCRIPTION
**Pull request by Longju000**
New sentences on:

### CODE REVIEW

**Review by schmelto — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
LGTM. 🙂👍

**Comment by Longju000** [comment]
Would love if there is any corrections to be done.
This is my first osp contribution.

**Comment by Longju000** [comment]
@eddiejaoude if you can check it out would appreciate your help.

**Comment by eddiejaoude** [comment]
> @eddiejaoude if you can check it out would appreciate your help.
Thank you for the changes @Longju000 , please be patient, I get 1000+ notifications per day and the community have already reviewed your changes and approved 🤓 

Thank you @schmelto and @Panquesito7 for reviewing

**Comment by Longju000** [comment]
> > @eddiejaoude if you can check it out would appreciate your help.
> > Thank you for the changes @Longju000, please be patient, I get 1000+ notifications per day and the community have already reviewed your changes and approved 🤓
> 
> Thank you @schmelto and @Panquesito7 for reviewing

Thanks, Eddie, it's my first time contributing to Open source, by following your youtube tutorial I have made my first contribution all thanks to you and the community.

**Comment by eddiejaoude** [comment]
Great work @Longju000 💥 keep going 💪

**Pull request merged**
