### PR TITLE
Corrected the typo and changed the Website URl in lighthouse-check.yml

### LINKED ISSUE #132: Typo in the portfolio
Screenshot (634)

### LINKED ISSUE #135: Automated tests are failing because of recent change in website URL
Pull Request Automated tests seem to be failing because they are still trying to reach https://eddiejaoudecommunity.github.io/ which is now https://eddiehubcommunity.github.io/.   

image
This should be easily fixed by updating the URL stored in [.github/workflows/lighthouse-check.yml](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/develop/.github/workflows/lighthouse-check.yml)

https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/7c3a07b8287738f67b60af2e73916a101cedf4e1/.github/workflows/lighthouse-check.yml#L20

### PR DESCRIPTION
**Pull request by Nitesh-thapliyal**
Close #132 
Close #135 
corrected typo "live Steaming" to "Live streaming"
Changed the Website URL in lighthouse-check.yml

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good  :+1: Thank You :smile:

**Comment by adityaraute** [comment]
It is a good idea to have one PR do only one thing. You could have fixed the typo in another one.

**Review by adityaraute — APPROVED** [review]

**Comment by Nitesh-thapliyal** [comment]
How can I create new PR on the same Repo as my last PR  is not merged? as soon I commit in the repo it directly gets added to my last PR.

**Comment by adityaraute** [comment]
You could create a new branch from the same base branch. Thus you will have one base branch, and two separate branches for each fix.

**Comment by Nitesh-thapliyal** [comment]
yes at the first time I forgot to create the branch 😅

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
