### PR TITLE
fix(tools): Update lighthouse

### PR DESCRIPTION
**Pull request by nhcarrigan**
Updates lighthouse to use new URL. This will resolve some CI failures on #136 and #133.

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Hmm, the lighthouse won't run against the new URL due to the `pull_request_target` option.

**Review by AllanRegush — DISMISSED** [review]
LGTM :+1:

**Review by adityaraute — APPROVED** [review]

**Comment by adityaraute** [comment]
I think #133 solves the same issue.

**Review by eddiejaoude — APPROVED** [review]
Thanks 👍

**Pull request merged**
