### PR TITLE
fix: updated website image at README.md (#128)

### LINKED ISSUE #128: READ.me file
i'm not sure but i think the read.me file has a screenshot of the home page of the website. Now that there is an update on the home page, is there a need to change the screenshot.

### PR DESCRIPTION
**Pull request by patel-himanshu**
Closes #128 
Updated the image of the website at README.md, with this [image file](https://user-images.githubusercontent.com/44549418/109976323-a7f24f80-7d21-11eb-8348-393b7ee10a8c.jpg).

### CODE REVIEW

**Review by AllanRegush — COMMENTED** [review]
Looks Good :+1: But when comparing the website to this image. It does not match.

**Comment by patel-himanshu** [comment]
Oh, the site got updated 44 minutes ago, after #147 was merged. I have fixed it now.

**Review by AllanRegush — APPROVED** [review]
LGTM :+1:

**Review by galahad42 — APPROVED** [review]
LGTM!

**Comment by jai-dewani** [comment]
LGTM! ✅   
Also I think we should open a new Issue about the website lighthouse score being less than 60 which failing the Lighthouse check

**Review by jai-dewani — APPROVED** [review]

**Review by SashoStoichkov — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
