### PR TITLE
Added Social Media Badge in README.md

### PR DESCRIPTION
**Pull request by dth99**
i.e. Twitter and LinkedIn

### CODE REVIEW

**Comment by Panquesito7** [comment]
Isn't this the same or a similar PR as #200? 🤔

**Comment by dth99** [comment]
> Isn't this the same or a similar PR as #200? thinking

There is some line gap between them. Overall, both of them are same

**Comment by Panquesito7** [comment]
> > Isn't this the same or a similar PR as #200? thinking
> 
> There is some line gap between them. Overall, both of them are same

I would recommend making a single pull request for that. 🙂

**Comment by dth99** [comment]
> > > Isn't this the same or a similar PR as #200? thinking
> > 
> > 
> > There is some line gap between them. Overall, both of them are same
> 
> I would recommend making a single pull request for that. slightly_smiling_face

Just check the last PR

**Comment by Panquesito7** [comment]
This is an exact duplicate of #200. I would recommend closing this one.

**Comment by dth99** [comment]
> This is an exact duplicate of #200. I would recommend closing this one.

closed

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thanks for your contribution! 😄👍

**Comment by dth99** [comment]
> LGTM rocket Thanks for your contribution! smile+1

thank you sir

**Comment by Panquesito7** [comment]
Just wondering: why did you close this PR? If it's closed, your changes won't be implemented. I recommend re-opening this PR if you want your changes to be added. 🙂

**Comment by dth99** [comment]
> Just wondering: why did you close this PR? If it's closed, your changes won't be implemented. I recommend re-opening this PR if you want your changes to be added. slightly_smiling_face

Sorry for this, Actually I'm making a some GitHub automation program using python. In testing for this tool, by mistake the repo was deleted. I made a new PR please check. 
sorry again for my mistake

**Pull request closed without merging**
