### PR TITLE
Add missing mod on community website.

### LINKED ISSUE #131: Missing Another Mod on the website!
Allan Regush, one of the discord moderators is missing on the community website.
https://eddiejaoudecommunity.github.io/

### PR DESCRIPTION
**Pull request by jcads**
Edited `src/data.js` to add @AllanRegush's profile.

Closes #131.

### CODE REVIEW

**Review by jai-dewani — COMMENTED** [review]
The new data added looks good to me, I don't know why the tests are failing.  
Also, there seem to be some changes coming in package-lock.json with this PR, are they needed or is this due to some changes that happened to the repo after this PR was created?

**Comment by Vyvy-vi** [comment]
@jcads  Maybe you can use npm-v6 rather than npm-v7 ?
(The package-lock looks like it's been touched with npm-v7 and that has breaking changes)

Could you perhaps revert the package-lock.json file to a version generated by npm-v6?

**Review by eddiejaoude — APPROVED** [review]
Looks good, thank you all 👍

**Comment by eddiejaoude** [comment]
Not sure why Cypress is still waiting, I think it should be ok

**Pull request merged**
