### PR TITLE
Changed image to iframe.

### PR DESCRIPTION
**Pull request by Prathamkrishna**
Screenshot (278)

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks @Prathamkrishna for creating another PR. But this looks the same as before with many line changes and not just the ones for this issue https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/125

**Comment by Prathamkrishna** [comment]
i just sent you a screenrecording on discord, i was not able to attach it here. please have a look at that. Also i think the changes in hundreds of lines is including the previous changes in the same file

**Comment by Prathamkrishna** [comment]
image

in the commits section.

**Comment by eddiejaoude** [comment]
Yep, this PR contains 2 commits. The first [commit](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/pull/129/commits/0e40e3edc44399fb8ea564d94c2f26bc60946c6f) looks good 👍 , but your PR contains a 2nd commit with all the reformatting changes

If you are able to create a PR with the first commit only, it will be easier to review and therefore get merged faster

**Comment by Prathamkrishna** [comment]
yep.. i have no idea why i cannot remove the second commit changes. Should i try deleting the fork of this repository on my profile
and then create a new fork/upload from my local system instead? And then try?

**Comment by Vyvy-vi** [comment]
I think you could try the following:
```
git clone https://github.com/Prathamkrishna/EddieJaoudeCommunity.github.io/
cd EddieJaoudeCommunity.github.io/
git checkout main
git revert 15effb5a23894c9944e742bf010f03ff1d645d14
git push
```

**Comment by eddiejaoude** [comment]
@Prathamkrishna oh sorry I did not realise that was the difficulty.

@Vyvy-vi idea is good 👍  - let us know how it goes and if you need anymore help

**Comment by Prathamkrishna** [comment]
Screenshot (280)

this is what it shows

**Comment by eddiejaoude** [comment]
The revert failed, it seems like it could not find that hash, double check the hash string in the history `git log`

**Comment by Vyvy-vi** [comment]
you might need to do `git fetch` and `git pull` and `git reset --hard` before the revert

**Comment by Prathamkrishna** [comment]
@eddiejaoude is it possible for you to remove the commit 2 while merging? i'm baffled by so much git bash,,

**Comment by adityaraute** [comment]
If it is too confusing, I would suggest to adopt a workaround and delete this PR altogether. Then create a new fork and do the changes in the first commit. Since it is a small change, shouldn't be difficult.

**Comment by eddiejaoude** [comment]
@Prathamkrishna no problem. I can not `cherry-pick` the commits, because it looks like the same line was changed in both commits with some improvements in both. I will manually take your latest line for the video and use that, but I will have to close the PR. Thank you for raising and you will still get the green squares for the work 🤓 

```html
<iframe width="960" height="545" src="https://www.youtube.com/embed/z-FKAC0I_VQ" frameborder="0" allow="accelerometer; clipboard-write; autoplay=1; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

```html
<iframe width="520" height="315" src="https://www.youtube.com/watch?v=z-FKAC0I_VQ&feature=youtu.be"></iframe>
```

**Comment by adityaraute** [comment]
> ...and you will still get the green squares for the work 🤓
 
How?

**Comment by eddiejaoude** [comment]
Green square from creating the issue and pull request, bt the commit will only count if in the default branch (in the remote or fork)

**Pull request closed without merging**
